{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c4fa884e-0e07-4dc5-8fed-e2ade016943e",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tkinter import *\n",
    "import tkinter as tk\n",
    "from tkinter import messagebox\n",
    "\n",
    "#Lớp BankAccount dùng để lưu trữ tài khoản\n",
    "class BankAccount:\n",
    "    accounts = {}  \n",
    "\n",
    "    def __init__(self, owner, balance=0):\n",
    "        self.owner = owner\n",
    "        self.balance = balance\n",
    "\n",
    "    def display_format(self):\n",
    "        return '{:,}'.format(int(self.balance)).replace(',', '.')\n",
    "\n",
    "    def amount_format(self, amount):\n",
    "        return '{:,}'.format(int(amount)).replace(',', '.')\n",
    "\n",
    "    def deposit(self, amount):\n",
    "        self.balance += amount\n",
    "        messagebox.showinfo('Thành công', f'Đã nạp {self.amount_format(amount)} VND vào tài khoản.\\nSố dư hiện tại: {self.display_format()} VND')\n",
    "\n",
    "    def withdraw(self, amount):\n",
    "        if self.balance >= amount:\n",
    "            if self.balance - amount >= 50000:\n",
    "                self.balance -= amount\n",
    "                messagebox.showinfo('Thành công!', f'Đã rút {self.amount_format(amount)} VND từ tài khoản.\\nSố dư hiện tại: {self.display_format()} VND')\n",
    "            else:\n",
    "                messagebox.showerror('Lỗi', 'Số dư tài khoản phải nhiều hơn 50.000 VND')\n",
    "        else:\n",
    "            messagebox.showerror('Lỗi', f'Số tiền trong tài khoản {self.owner} không đủ để giao dịch')\n",
    "\n",
    "    def display_balance(self):\n",
    "        messagebox.showinfo('Thông tin tài khoản', f'Chủ tài khoản: {self.owner}\\nSố dư tài khoản: {self.display_format()} VND')\n",
    "\n",
    "    @classmethod\n",
    "    def signup(cls, username_entry, password_entry, confirm_password_entry, signup_window):\n",
    "        username = username_entry.get()\n",
    "        password = password_entry.get()\n",
    "        conpw = confirm_password_entry.get()\n",
    "        if not username or not password or not conpw:\n",
    "            messagebox.showerror('Lỗi', 'Vui lòng điền đầy đủ thông tin')\n",
    "            return\n",
    "        if username in cls.accounts:\n",
    "            messagebox.showerror('Lỗi', 'Tên đăng nhập đã tồn tại')\n",
    "            return\n",
    "        if password != conpw:\n",
    "            messagebox.showerror('Lỗi', 'Mật khẩu không trùng khớp')\n",
    "            return\n",
    "        cls.accounts[username] = BankAccount(username) \n",
    "        messagebox.showinfo('Thành công', 'Đã tạo tài khoản thành công!')\n",
    "        signup_window.destroy()\n",
    "        loginScreen()\n",
    "\n",
    "    @classmethod\n",
    "    def login(cls, username_entry, password_entry, login_window):\n",
    "        username = username_entry.get()\n",
    "        password = password_entry.get()\n",
    "\n",
    "        if not username or not password:\n",
    "            messagebox.showerror('Lỗi', 'Vui lòng điền đầy đủ tên đăng nhập và mật khẩu')\n",
    "            return\n",
    "\n",
    "        if username in cls.accounts:\n",
    "            messagebox.showinfo('Thành công', 'Đăng nhập thành công!')\n",
    "            login_window.destroy()\n",
    "            mainmenu(username)\n",
    "        else:\n",
    "            messagebox.showerror('Lỗi', 'Tên đăng nhập không tồn tại')\n",
    "\n",
    "#Thiết lập mẫu màn hình\n",
    "def screen():\n",
    "    screen_win = Tk()\n",
    "    screen_win.title('Ngân hàng Miền Tây E-Banking')\n",
    "    screen_win.geometry('500x400')\n",
    "    screen_win.resizable(False, False)\n",
    "    screen_win.config(bg='#c644a1')\n",
    "    return screen_win\n",
    "\n",
    "#Giao diện tiêu đề\n",
    "def title(ScreenTitle):\n",
    "    ATMTitle = Label(ScreenTitle, text='NGÂN HÀNG MIỀN TÂY', font=('Times News Roman', 30, 'bold'), fg='white', bg='#c644a1')\n",
    "    ATMTitle.place(x=20, y=25)\n",
    "    ATMSlogan = Label(ScreenTitle, text='Chu đáo - Tận tâm - Nhiệt tình', font=('Times New Roman', 20), fg='white', bg='#c644a1')\n",
    "    ATMSlogan.place(x=80, y=70)\n",
    "\n",
    "#Màn hình đăng nhập\n",
    "def loginScreen():\n",
    "    LoginScreen = screen()\n",
    "    title(LoginScreen)\n",
    "    Username = Label(LoginScreen, text='Số tài khoản:', font=('Arial', 15, 'bold'), fg='white', bg='#c644a1')\n",
    "    Username.place(x=40, y=160)\n",
    "    Userinput = tk.Entry(LoginScreen, width=30, highlightthickness=2)\n",
    "    Userinput.place(x=200, y=167)\n",
    "    PW = Label(LoginScreen, text='Mật khẩu:', font=('Arial', 15, 'bold'), fg='white', bg='#c644a1')\n",
    "    PW.place(x=40, y=200)\n",
    "    PWInput = tk.Entry(LoginScreen, width=25, highlightthickness=2, show='*')\n",
    "    PWInput.place(x=200, y=207)\n",
    "    LoginBtn = tk.Button(LoginScreen, text='Đăng nhập', font=('Arial', 10), padx=15, command=lambda: BankAccount.login(Userinput, PWInput, LoginScreen))\n",
    "    LoginBtn.place(x=120, y=270)\n",
    "    SigninBtn = tk.Button(LoginScreen, text='Đăng ký', font=('Arial', 10), padx=15, command=lambda: to_signupScreen(LoginScreen))\n",
    "    SigninBtn.place(x=230, y=270)\n",
    "    LoginScreen.mainloop()\n",
    "\n",
    "#Chuyển đến màn hình đắng ký\n",
    "def to_signupScreen(login):\n",
    "    login.destroy()\n",
    "    signupScreen()\n",
    "\n",
    "#Màn hình đăng ký\n",
    "def signupScreen():\n",
    "    SignupScreen = screen()\n",
    "    title(SignupScreen)\n",
    "    Username = Label(SignupScreen, text='Số tài khoản:', font=('Arial', 15, 'bold'), fg='white', bg='#c644a1')\n",
    "    Username.place(x=20, y=160)\n",
    "    UsernameInput = tk.Entry(SignupScreen, width=30, highlightthickness=2)\n",
    "    UsernameInput.place(x=220, y=167)\n",
    "    PWLabel = Label(SignupScreen, text='Mật khẩu:', font=('Arial', 15, 'bold'), fg='white', bg='#c644a1')\n",
    "    PWLabel.place(x=20, y=200)\n",
    "    PWInput = tk.Entry(SignupScreen, width=25, highlightthickness=2, show='*')\n",
    "    PWInput.place(x=220, y=207)\n",
    "    Conpw = Label(SignupScreen, text='Xác nhận mật khẩu:', font=('Arial', 15, 'bold'), fg='white', bg='#c644a1')\n",
    "    Conpw.place(x=20, y=240)\n",
    "    ConpwInput = tk.Entry(SignupScreen, width=25, highlightthickness=2, show='*')\n",
    "    ConpwInput.place(x=220, y=247)\n",
    "    SigninBtn = tk.Button(SignupScreen, text='Đăng ký', font=('Arial', 10), padx=15, command=lambda: BankAccount.signup(UsernameInput, PWInput, ConpwInput, SignupScreen))\n",
    "    SigninBtn.place(x=180, y=300)\n",
    "    LoginMes = Label(SignupScreen, text='Đã có tài khoản?', font=('Arial', 12, 'bold'), fg='white', bg='#c644a1')\n",
    "    LoginMes.place(x=90, y=340)\n",
    "    LoginBtn = tk.Button(SignupScreen, text='Đăng nhập', font=('Arial', 10), padx=10, command=lambda: to_loginscreen(SignupScreen))\n",
    "    LoginBtn.place(x=250, y=340)\n",
    "    SignupScreen.mainloop()\n",
    "\n",
    "#Chuyển đến màn hình đăng nhập\n",
    "def to_loginscreen(signup):\n",
    "    signup.destroy()\n",
    "    loginScreen()\n",
    "\n",
    "#Màn hình chính sau khi đăng nhập thành công\n",
    "def mainmenu(username):\n",
    "    MainScreen = screen()\n",
    "    title(MainScreen)\n",
    "    MainMenu = Label(MainScreen, text='Menu chính:', font=('Arial', 20, 'bold'), fg='white', bg='#c644a1')\n",
    "    MainMenu.place(x=20, y=130)\n",
    "\n",
    "    def display_balance_command():\n",
    "        if username in BankAccount.accounts:\n",
    "            BankAccount.accounts[username].display_balance()\n",
    "        else:\n",
    "            messagebox.showerror('Lỗi', 'Không tìm thấy tài khoản.')\n",
    "\n",
    "    def deposit_command():\n",
    "        if username in BankAccount.accounts:\n",
    "            deposit_window(BankAccount.accounts[username])\n",
    "        else:\n",
    "            messagebox.showerror('Lỗi', 'Không tìm thấy tài khoản.')\n",
    "\n",
    "    def withdraw_command():\n",
    "        if username in BankAccount.accounts:\n",
    "            withdraw_window(BankAccount.accounts[username])\n",
    "        else:\n",
    "            messagebox.showerror('Lỗi', 'Không tìm thấy tài khoản.')\n",
    "\n",
    "    ThongTinKH = tk.Button(MainScreen, text='Thông tin khách hàng', font=('Arial', 10), width=20, command=display_balance_command)\n",
    "    ThongTinKH.place(x=50, y=170)\n",
    "    GuiTien = tk.Button(MainScreen, text='Nạp tiền vào tài khoản', font=('Arial', 10), width=20, command=deposit_command)\n",
    "    GuiTien.place(x=50, y=210)\n",
    "    RutTien = tk.Button(MainScreen, text='Rút tiền từ tài khoản', font=('Arial', 10), width=20, command=withdraw_command)\n",
    "    RutTien.place(x=50, y=250)\n",
    "    DangXuat = tk.Button(MainScreen, text='Đăng xuất', font=('Arial', 10), padx=5, command=lambda: logout(MainScreen))\n",
    "    DangXuat.place(x=210, y=310)\n",
    "    LoginSuc = Label(MainScreen, text=f'Chào mừng {username}!', font=('Arial', 12, 'bold'), fg='white', bg='#aa2b61')\n",
    "    MainScreen.update_idletasks()\n",
    "    screen_width = MainScreen.winfo_width()\n",
    "    label_width = LoginSuc.winfo_reqwidth() \n",
    "    x_position = (screen_width - label_width) // 2\n",
    "    LoginSuc.place(x=x_position, y=350)\n",
    "    MainScreen.mainloop()\n",
    "\n",
    "#Màn hình chức năng nạp tiền\n",
    "def deposit_window(account):\n",
    "    deposit_win = Toplevel()\n",
    "    deposit_win.title('Nạp tiền')\n",
    "    deposit_win.geometry('300x150')\n",
    "    deposit_win.config(bg='#e0f2f7')\n",
    "\n",
    "    amount_label = Label(deposit_win, text='Số tiền nạp:', font=('Arial', 12), bg='#e0f2f7')\n",
    "    amount_label.pack(pady=10)\n",
    "    amount_entry = tk.Entry(deposit_win, width=20)\n",
    "    amount_entry.pack()\n",
    "\n",
    "    def perform_deposit():\n",
    "        try:\n",
    "            amount = float(amount_entry.get())\n",
    "            if amount > 0:\n",
    "                account.deposit(amount)\n",
    "                deposit_win.destroy()\n",
    "            else:\n",
    "                messagebox.showerror('Lỗi', 'Vui lòng nhập số tiền hợp lệ.')\n",
    "        except ValueError:\n",
    "            messagebox.showerror('Lỗi', 'Vui lòng nhập số tiền hợp lệ.')\n",
    "\n",
    "    deposit_button = tk.Button(deposit_win, text='Nạp tiền', command=perform_deposit)\n",
    "    deposit_button.pack(pady=10)\n",
    "\n",
    "#Màn hình chức năng rút tiền\n",
    "def withdraw_window(account):\n",
    "    withdraw_win = Toplevel()\n",
    "    withdraw_win.title('Rút tiền')\n",
    "    withdraw_win.geometry('300x150')\n",
    "    withdraw_win.config(bg='#e0f2f7')\n",
    "\n",
    "    amount_label = Label(withdraw_win, text='Số tiền rút:', font=('Arial', 12), bg='#e0f2f7')\n",
    "    amount_label.pack(pady=10)\n",
    "    amount_entry = tk.Entry(withdraw_win, width=20)\n",
    "    amount_entry.pack()\n",
    "\n",
    "    def perform_withdraw():\n",
    "        try:\n",
    "            amount = float(amount_entry.get())\n",
    "            if amount > 0:\n",
    "                account.withdraw(amount)\n",
    "                withdraw_win.destroy()\n",
    "            else:\n",
    "                messagebox.showerror('Lỗi', 'Vui lòng nhập số tiền hợp lệ.')\n",
    "        except ValueError:\n",
    "            messagebox.showerror('Lỗi', 'Vui lòng nhập số tiền hợp lệ.')\n",
    "\n",
    "    withdraw_button = tk.Button(withdraw_win, text='Rút tiền', command=perform_withdraw)\n",
    "    withdraw_button.pack(pady=10)\n",
    "\n",
    "#Đăng xuất khỏi màn chính\n",
    "def logout(current_screen):\n",
    "    current_screen.destroy()\n",
    "    loginScreen()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    loginScreen()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9df63cf6-b507-47db-8823-9af35b19db9a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
